markdown: kramdown
url: ''
baseurl: ''
title: Jesus Rodriguez
description: 'Fullstack Mobille Developer using Flutter, NodeJS y Google Cloud'
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Mobile Developer, Scrum Master, Flutter, NodeJs,'
favicon-url: null
heroimage: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
email: mascreativosdev@gmail.com
facebook_username: ''
twitter_username: ''
instagram_username: chuy_.rodriguez
linkedin_username: jesús-rodríguez-14a297179
github_username: Jes-us
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: jessrodriguez21
dribbble_username: /
spotify_username: /
google-analytics: UA-163806439-1
disqus-shortname: Jesus Rodriguez
author-name: Jesus Rodriguez
author-image: /assets/images/author.jpeg
author-about: >-
  Soy un desarrollador de aplicaciones para dispositivos móviles apasionado por
  crear experiencias de usuario cautivadoras. Mi enfoque se centra en combinar
  un diseño intuitivo con una arquitectura robusta que facilite la creación de
  código escalable y mantenible.

   Además de mi experiencia en desarrollo móvil, tengo una sólida trayectoria en el desarrollo de backend, lo que me permite integrar de manera efectiva la lógica del servidor con las interfaces de usuario. Esta combinación de habilidades me permite ofrecer soluciones completas que no solo cumplen con los requisitos funcionales, sino que también garantizan un rendimiento óptimo y una excelente experiencia para el usuario.
author-url: www.linkedin.com/in/jesús-rodríguez-14a297179
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
