markdown: kramdown
url: ''
baseurl: null
title: Jesus Rodriguez
description: 'Fullstack Mobille Developer using Flutter, NodeJS y Google Cloud'
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Mobile Developer, Scrum Master, Flutter, NodeJs,'
favicon-url: null
heroimage: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
email: mascreativosdev@gmail.com
facebook_username: ''
twitter_username: ''
instagram_username: chuy_.rodriguez
linkedin_username: jesús-rodríguez-14a297179
github_username: Jes-us
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: jessrodriguez21
dribbble_username: /
spotify_username: /
google-analytics: UA-163806439-1
disqus-shortname: Jesus Rodriguez
author-name: Jesus Rodriguez
author-image: /assets/images/author.jpeg
author-about: >-
  Soy un profesional creativo, me encanta convertir ideas en nuevos productos,
  muy enfocado en resultados, trabajo en equipo, poseo buenas habilidades
  técnicas, resolución de problemas y muy buenas habilidades de comunicación.
author-url: www.linkedin.com/in/jesús-rodríguez-14a297179
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
